default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: campusilan_development

test:
  <<: *default
  database: campusilan_test

production:
  <<: *default
  database: campusilan_production