default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  
development:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: campusilan_development
  

test:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: campusilan_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
