# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c755fef21197cc32828829e8d14280f0531f4fca91b5e36cf915d57aa299cc3ed6399028bdc065f2aee77101445eece30a9ff914cf2f8c98570fdbb55939fc2

test:
  secret_key_base: f943caa1bc766f2d39d5488d016bd2643c8cdc51d3783a1214fc80766c6bb3ff1ea1d4a1f3e50a565a9d7742c45b675c64a598ee7cf90e21bb38d0ed9f89c168

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
