University.create( :name => 'ORTA DOĞU TEKNİK ÜNİVERSİTESİ', :email => 'metu.edu.tr' )
University.create(:name => 'ABANT İZZET BAYSAL ÜNİVERSİTESİ', :email => 'ibu.edu.tr')
University.create(:name => 'ABDULLAH GÜL ÜNİVERSİTESİ', :email => 'agu.edu.tr')
University.create(:name => 'ACIBADEM ÜNİVERSİTESİ', :email => 'acibadem.edu.tr')
University.create(:name => 'ADANA BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ', :email => 'adanabtu.edu.tr')
University.create(:name => 'ADIYAMAN ÜNİVERSİTESİ', :email => 'adiyaman.edu.tr')
University.create(:name => 'ADNAN MENDERES ÜNİVERSİTESİ', :email => 'adu.edu.tr')
University.create(:name => 'AFYON KOCATEPE ÜNİVERSİTESİ', :email => 'aku.edu.tr')
University.create(:name => 'AĞRI İBRAHİM ÇEÇEN ÜNİVERSİTESİ', :email => 'agri.edu.tr')
University.create(:name => 'AHİ EVRAN ÜNİVERSİTESİ', :email => 'ahievran.edu.tr')
University.create(:name => 'AKDENİZ ÜNİVERSİTESİ', :email => 'akdeniz.edu.tr')
University.create(:name => 'AKSARAY ÜNİVERSİTESİ', :email => 'aksaray.edu.tr')
#University.create(:name => 'ALANYA ALAADDİN KEYKUBAT ÜNİVERSİTESİ', :email => 'akdeniz.edu.tr')
University.create(:name => 'ALANYA HAMDULLAH EMİN PAŞA ÜNİVERSİTESİ', :email => 'ahep.edu.tr')
University.create(:name => 'AMASYA ÜNİVERSİTESİ', :email => 'amasya.edu.tr')
University.create(:name => 'ANADOLU ÜNİVERSİTESİ', :email => 'anadolu.edu.tr')
#University.create(:name => 'ANKA TEKNOLOJİ ÜNİVERSİTESİ', :email => '')
University.create(:name => 'ANKARA SOSYAL BİLİMLER ÜNİVERSİTESİ', :email => 'asbu.edu.tr')
University.create(:name => 'ANKARA ÜNİVERSİTESİ', :email => 'ankara.edu.tr')
#University.create(:name => 'ANTALYA AKEV ÜNİVERSİTESİ', :email => 'adiyaman.edu.tr')
University.create(:name => 'ARDAHAN ÜNİVERSİTESİ', :email => 'ardahan.edu.tr')
University.create(:name => 'ARTVİN ÇORUH ÜNİVERSİTESİ', :email => 'artvin.edu.tr')
University.create(:name => 'ATAŞEHİR ADIGÜZEL MESLEK YÜKSEKOKULU', :email => 'adiguzel.edu.tr')
University.create(:name => 'ATATÜRK ÜNİVERSİTESİ', :email => 'atauni.edu.tr')
University.create(:name => 'ATILIM ÜNİVERSİTESİ', :email => 'atilim.edu.tr')
University.create(:name => 'AVRASYA ÜNİVERSİTESİ', :email => 'avrasya.edu.tr')
University.create(:name => 'AVRUPA MESLEK YÜKSEKOKULU', :email => 'avrupa.edu.tr')
University.create(:name => 'BAHÇEŞEHİR ÜNİVERSİTESİ', :email => 'bahcesehir.edu.tr')
University.create(:name => 'BALIKESİR ÜNİVERSİTESİ', :email => 'balikesir.edu.tr')
University.create(:name => 'BANDIRMA ONYEDİ EYLÜL ÜNİVERSİTESİ', :email => 'bandirma.edu.tr')
University.create(:name => 'BARTIN ÜNİVERSİTESİ', :email => 'bartin.edu.tr')
University.create(:name => 'BAŞKENT ÜNİVERSİTESİ', :email => 'baskent.edu.tr')
University.create(:name => 'BATMAN ÜNİVERSİTESİ', :email => 'batman.edu.tr')
University.create(:name => 'BAYBURT ÜNİVERSİTESİ', :email => 'bayburt.edu.tr')
University.create(:name => 'BEYKENT ÜNİVERSİTESİ', :email => 'beykent.edu.tr')
University.create(:name => 'BEYKOZ LOJİSTİK MESLEK YÜKSEKOKULU', :email => 'beykoz.edu.tr')
University.create(:name => 'BEZM-İ ALEM VAKIF ÜNİVERSİTESİ', :email => 'bezmialem.edu.tr')
University.create(:name => 'BİLECİK ŞEYH EDEBALI ÜNİVERSİTESİ', :email => 'bilecik.edu.tr')
University.create(:name => 'BİNGÖL ÜNİVERSİTESİ', :email => 'bingol.edu.tr')
University.create(:name => 'BİRUNİ ÜNİVERSİTESİ', :email => 'biruni.edu.tr')
University.create(:name => 'BİTLİS EREN ÜNİVERSİTESİ', :email => 'beu.edu.tr')
University.create(:name => 'BOĞAZİÇİ ÜNİVERSİTESİ', :email => 'boun.edu.tr')
University.create(:name => 'BOZOK ÜNİVERSİTESİ', :email => 'bozok.edu.tr')
University.create(:name => 'BURSA ORHANGAZİ ÜNİVERSİTESİ', :email => 'bou.edu.tr')
University.create(:name => 'BURSA TEKNİK ÜNİVERSİTESİ', :email => 'btu.edu.tr')
University.create(:name => 'BÜLENT ECEVİT ÜNİVERSİTESİ', :email => 'beun.edu.tr')
University.create(:name => 'CANİK BAŞARI ÜNİVERSİTESİ', :email => 'basari.edu.tr')
University.create(:name => 'CELAL BAYAR ÜNİVERSİTESİ', :email => 'cbu.edu.tr')
University.create(:name => 'CUMHURİYET ÜNİVERSİTESİ', :email => 'cumhuriyet.edu.tr')
University.create(:name => 'ÇAĞ ÜNİVERSİTESİ', :email => 'cag.edu.tr')
University.create(:name => 'ÇANAKKALE ONSEKİZ MART ÜNİVERSİTESİ', :email => 'comu.edu.tr')
University.create(:name => 'ÇANKAYA ÜNİVERSİTESİ', :email => 'cankaya.edu.tr')
University.create(:name => 'ÇANKIRI KARATEKİN ÜNİVERSİTESİ', :email => 'karatekin.edu.tr')
University.create(:name => 'ÇUKUROVA ÜNİVERSİTESİ', :email => 'cukurova.edu.tr')
University.create(:name => 'DİCLE ÜNİVERSİTESİ', :email => 'dicle.edu.tr')
University.create(:name => 'DOĞUŞ ÜNİVERSİTESİ', :email => 'dogus.edu.tr')
University.create(:name => 'DOKUZ EYLÜL ÜNİVERSİTESİ', :email => 'deu.edu.tr')
University.create(:name => 'DUMLUPINAR ÜNİVERSİTESİ', :email => 'dpu.edu.tr')
University.create(:name => 'DÜZCE ÜNİVERSİTESİ', :email => 'duzce.edu.tr')
University.create(:name => 'EGE ÜNİVERSİTESİ', :email => 'mail.ege.edu.tr')
University.create(:name => 'ERCİYES ÜNİVERSİTESİ', :email => 'erciyes.edu.tr')
University.create(:name => 'ERZİNCAN ÜNİVERSİTESİ', :email => 'erzincan.edu.tr')
University.create(:name => 'ERZURUM TEKNİK ÜNİVERSİTESİ', :email => 'erzurum.edu.tr')
University.create(:name => 'ESKİŞEHİR OSMANGAZİ ÜNİVERSİTESİ', :email => 'ogu.edu.tr')
University.create(:name => 'FARUK SARAÇ TASARIM MESLEK YÜKSEKOKULU', :email => 'faruksarac.edu.tr')
University.create(:name => 'FATİH SULTAN MEHMET VAKIF ÜNİVERSİTESİ', :email => 'fsm.edu.tr')
University.create(:name => 'FIRAT ÜNİVERSİTESİ', :email => 'firat.edu.tr')
University.create(:name => 'GALATASARAY ÜNİVERSİTESİ', :email => 'gsu.edu.tr')
University.create(:name => 'GAZİ ÜNİVERSİTESİ', :email => 'gazi.edu.tr')
University.create(:name => 'GAZİANTEP ÜNİVERSİTESİ', :email => 'gantep.edu.tr')
University.create(:name => 'GAZİOSMANPAŞA ÜNİVERSİTESİ', :email => 'gop.edu.tr')
University.create(:name => 'GEBZE TEKNİK ÜNİVERSİTESİ', :email => 'gyte.edu.tr')
University.create(:name => 'GEDİK ÜNİVERSİTESİ', :email => 'gedik.edu.tr')
University.create(:name => 'GEDİZ ÜNİVERSİTESİ', :email => 'gediz.edu.tr')
University.create(:name => 'GİRESUN ÜNİVERSİTESİ', :email => 'giresun.edu.tr')
University.create(:name => 'GÜMÜŞHANE ÜNİVERSİTESİ', :email => 'gumushane.edu.tr')
University.create(:name => 'HACETTEPE ÜNİVERSİTESİ', :email => 'hacettepe.edu.tr')
University.create(:name => 'HAKKARİ ÜNİVERSİTESİ', :email => 'hakkari.edu.tr')
University.create(:name => 'HALİÇ ÜNİVERSİTESİ', :email => 'halic.edu.tr')
University.create(:name => 'HARRAN ÜNİVERSİTESİ', :email => 'harran.edu.tr')
University.create(:name => 'HASAN KALYONCU ÜNİVERSİTESİ', :email => 'hku.edu.tr')
University.create(:name => 'HİTİT ÜNİVERSİTESİ', :email => 'hitit.edu.tr')
University.create(:name => 'IĞDIR ÜNİVERSİTESİ', :email => 'igdir.edu.tr')
University.create(:name => 'IŞIK ÜNİVERSİTESİ', :email => 'isikun.edu.tr')
#University.create(:name => 'İBN HALDUN ÜNİVERSİTESİ', :email => ')
University.create(:name => 'İHSAN DOĞRAMACI BİLKENT ÜNİVERSİTESİ', :email => 'bilkent.edu.tr')
University.create(:name => 'İNÖNÜ ÜNİVERSİTESİ', :email => 'inonu.edu.tr')
University.create(:name => 'İPEK ÜNİVERSİTESİ', :email => 'ipek.edu.tr')
University.create(:name => 'İSKENDERUN TEKNİK ÜNİVERSİTESİ', :email => 'istek.edu.tr')
University.create(:name => 'İSTANBUL AREL ÜNİVERSİTESİ', :email => 'arel.edu.tr')
University.create(:name => 'İSTANBUL AYDIN ÜNİVERSİTESİ', :email => 'aydin.edu.tr')
University.create(:name => 'İSTANBUL BİLGİ ÜNİVERSİTESİ', :email => 'bilgi.edu.tr')
University.create(:name => 'İSTANBUL BİLİM ÜNİVERSİTESİ', :email => 'istanbulbilim.edu.tr')
University.create(:name => 'İSTANBUL ESENYURT ÜNİVERSİTESİ', :email => 'esenyurt.edu.tr')
University.create(:name => 'İSTANBUL GELİŞİM ÜNİVERSİTESİ', :email => 'gelisim.edu.tr')
University.create(:name => 'İSTANBUL KAVRAM MESLEK YÜKSEKOKULU', :email => 'kavram.edu.tr')
University.create(:name => 'İSTANBUL KEMERBURGAZ ÜNİVERSİTESİ', :email => 'kemerburgaz.edu.tr')
University.create(:name => 'İSTANBUL KÜLTÜR ÜNİVERSİTESİ', :email => 'iku.edu.tr')
University.create(:name => 'İSTANBUL MEDENİYET ÜNİVERSİTESİ', :email => 'medeniyet.edu.tr')
University.create(:name => 'İSTANBUL MEDİPOL ÜNİVERSİTESİ', :email => 'medipol.edu.tr')
University.create(:name => 'İSTANBUL RUMELİ ÜNİVERSİTESİ', :email => 'rumeli.edu.tr')
University.create(:name => 'İSTANBUL SABAHATTİN ZAİM ÜNİVERSİTESİ', :email => 'izu.edu.tr')
University.create(:name => 'İSTANBUL ŞEHİR ÜNİVERSİTESİ', :email => 'sehir.edu.tr')
University.create(:name => 'İSTANBUL ŞİŞLİ MESLEK YÜKSEKOKULU', :email => 'sisli.edu.tr')
University.create(:name => 'İSTANBUL TEKNİK ÜNİVERSİTESİ', :email => 'itu.edu.tr')
University.create(:name => 'İSTANBUL TİCARET ÜNİVERSİTESİ', :email => 'ticaret.edu.tr')
University.create(:name => 'İSTANBUL ÜNİVERSİTESİ', :email => 'istanbul.edu.tr')
University.create(:name => 'İSTANBUL 29 MAYIS ÜNİVERSİTESİ', :email => '29mayis.edu.tr')
#University.create(:name => 'İSTİNYE ÜNİVERSİTESİ', :email => '')
University.create(:name => 'İZMİR EKONOMİ ÜNİVERSİTESİ', :email => 'ieu.edu.tr')
University.create(:name => 'İZMİR KATİP ÇELEBİ ÜNİVERSİTESİ', :email => 'ikc.edu.tr')
University.create(:name => 'İZMİR ÜNİVERSİTESİ', :email => 'izmir.edu.tr')
University.create(:name => 'İZMİR YÜKSEK TEKNOLOJİ ENSTİTÜSÜ', :email => 'iyte.edu.tr')
University.create(:name => 'KADİR HAS ÜNİVERSİTESİ', :email => 'khas.edu.tr')
University.create(:name => 'KAFKAS ÜNİVERSİTESİ', :email => 'kafkas.edu.tr')
University.create(:name => 'KAHRAMANMARAŞ SÜTÇÜ İMAM ÜNİVERSİTESİ', :email => 'ksu.edu.tr')
University.create(:name => 'KANUNİ ÜNİVERSİTESİ', :email => 'kanuni.edu.tr')
University.create(:name => 'KAPADOKYA MESLEK YÜKSEKOKULU', :email => 'kapadokya.edu.tr')
University.create(:name => 'KARABÜK ÜNİVERSİTESİ', :email => 'karabuk.edu.tr')
University.create(:name => 'KARADENİZ TEKNİK ÜNİVERSİTESİ', :email => 'ktu.edu.tr')
University.create(:name => 'KARAMANOĞLU MEHMETBEY ÜNİVERSİTESİ', :email => 'kmu.edu.tr')
University.create(:name => 'KASTAMONU ÜNİVERSİTESİ', :email => 'kastamonu.edu.tr')
University.create(:name => 'KIRIKKALE ÜNİVERSİTESİ', :email => 'kku.edu.tr')
University.create(:name => 'KIRKLARELİ ÜNİVERSİTESİ', :email => 'kirklareli.edu.tr')
University.create(:name => 'KİLİS 7 ARALIK ÜNİVERSİTESİ', :email => 'kilis.edu.tr')
University.create(:name => 'KOCAELİ ÜNİVERSİTESİ', :email => 'kocaeli.edu.tr')
University.create(:name => 'KOÇ ÜNİVERSİTESİ', :email => 'ku.edu.tr')
University.create(:name => 'KONYA GIDA VE TARIM ÜNİVERSİTESİ', :email => 'gidatarim.edu.tr')
University.create(:name => 'KTO KARATAY ÜNİVERSİTESİ', :email => 'karatay.edu.tr')
University.create(:name => 'MALTEPE ÜNİVERSİTESİ', :email => 'maltepe.edu.tr')
University.create(:name => 'MARDİN ARTUKLU ÜNİVERSİTESİ', :email => 'artuklu.edu.tr')
#University.create(:name => 'MARMARA ÜNİVERSİTESİ', :email => '')
University.create(:name => 'MEF ÜNİVERSİTESİ', :email => 'mef.edu.tr')
University.create(:name => 'MEHMET AKİF ERSOY ÜNİVERSİTESİ', :email => 'mehmetakif.edu.tr')
University.create(:name => 'MELİKŞAH ÜNİVERSİTESİ', :email => 'meliksah.edu.tr')
University.create(:name => 'MERSİN ÜNİVERSİTESİ', :email => 'mersin.edu.tr')
University.create(:name => 'MEVLANA ÜNİVERSİTESİ', :email => 'mevlana.edu.tr')
University.create(:name => 'MİMAR SİNANGÜZEL SANATLAR ÜNİVERSİTESİ', :email => 'msgsu.edu.tr')
University.create(:name => 'MUĞLA SITKI KOÇMAN ÜNİVERSİTESİ', :email => 'mu.edu.tr')
University.create(:name => 'MURAT HÜDAVENDİGAR ÜNİVERSİTESİ', :email => 'mhu.edu.tr')
University.create(:name => 'MUSTAFA KEMAL ÜNİVERSİTESİ', :email => 'mku.edu.tr')
University.create(:name => 'MUŞ ALPARSLAN ÜNİVERSİTESİ', :email => 'alparslan.edu.tr')
University.create(:name => 'NAMIK KEMAL ÜNİVERSİTESİ', :email => 'nku.edu.tr')
University.create(:name => 'NECMETTİN ERBAKAN ÜNİVERSİTESİ', :email => 'konya.edu.tr')
University.create(:name => 'NEVŞEHİR HACI BEKTAŞ VELİ ÜNİVERSİTESİ', :email => 'nevsehir.edu.tr')
University.create(:name => 'NİĞDE ÜNİVERSİTESİ', :email => 'nigde.edu.tr')
University.create(:name => 'NİŞANTAŞI ÜNİVERSİTESİ', :email => 'nisantasi.edu.tr')
University.create(:name => 'NUH NACİ YAZGAN ÜNİVERSİTESİ', :email => 'nny.edu.tr')
University.create(:name => 'OKAN ÜNİVERSİTESİ', :email => 'okan.edu.tr')
University.create(:name => 'ONDOKUZ MAYIS ÜNİVERSİTESİ', :email => 'omu.edu.tr')
University.create(:name => 'ORDU ÜNİVERSİTESİ', :email => 'odu.edu.tr')
University.create(:name => 'OSMANİYE KORKUT ATA ÜNİVERSİTESİ', :email => 'osmaniye.edu.tr')
University.create(:name => 'ÖZYEĞİN ÜNİVERSİTESİ', :email => 'ozyegin.edu.tr')
University.create(:name => 'PAMUKKALE ÜNİVERSİTESİ', :email => 'pau.edu.tr')
University.create(:name => 'PİRİ REİS ÜNİVERSİTESİ', :email => 'pirireis.edu.tr')
University.create(:name => 'PLATO MESLEK YÜKSEKOKULU', :email => 'plato.edu.tr')
University.create(:name => 'RECEP TAYYİP ERDOĞAN ÜNİVERSİTESİ', :email => 'erdogan.edu.tr')
University.create(:name => 'SABANCI ÜNİVERSİTESİ', :email => 'sabanciuniv.edu.tr')
#University.create(:name => 'SAĞLIK BİLİMLERİ ÜNİVERSİTESİ', :email => 'okan.edu.tr')
University.create(:name => 'SAKARYA ÜNİVERSİTESİ', :email => 'sakarya.edu.tr')
University.create(:name => 'SANKO ÜNİVERSİTESİ', :email => 'sanko.edu.tr')
University.create(:name => 'SELAHADDİN EYYUBİ ÜNİVERSİTESİ', :email => 'seu.edu.tr')
University.create(:name => 'SELÇUK ÜNİVERSİTESİ', :email => 'selcuk.edu.tr')
University.create(:name => 'SİİRT ÜNİVERSİTESİ', :email => 'siirt.edu.tr')
University.create(:name => 'SİNOP ÜNİVERSİTESİ', :email => 'sinop.edu.tr')
University.create(:name => 'SÜLEYMAN DEMİREL ÜNİVERSİTESİ', :email => 'sdu.edu.tr')
University.create(:name => 'SÜLEYMAN ŞAH ÜNİVERSİTESİ', :email => 'ssu.edu.tr')
University.create(:name => 'ŞIRNAK ÜNİVERSİTESİ', :email => 'sirnak.edu.tr')
University.create(:name => 'ŞİFA ÜNİVERSİTESİ', :email => 'sifa.edu.tr')
University.create(:name => 'TED ÜNİVERSİTESİ', :email => 'tedu.edu.tr')
University.create(:name => 'TOBB EKONOMİ VE TEKNOLOJİ ÜNİVERSİTESİ', :email => 'etu.edu.tr')
University.create(:name => 'TOROS ÜNİVERSİTESİ', :email => 'toros.edu.tr')
University.create(:name => 'TRAKYA ÜNİVERSİTESİ', :email => 'trakya.edu.tr')
University.create(:name => 'TUNCELİ ÜNİVERSİTESİ', :email => 'tunceli.edu.tr')
University.create(:name => 'TURGUT ÖZAL ÜNİVERSİTESİ', :email => 'turgutozal.edu.tr')
University.create(:name => 'TÜRK HAVA KURUMU ÜNİVERSİTESİ', :email => 'thk.edu.tr')
University.create(:name => 'TÜRK-ALMAN ÜNİVERSİTESİ', :email => 'tau.edu.tr')
#University.create(:name => 'TÜRKİYE ULUSLARARASI İSLAM, BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ', :email => '')
University.create(:name => 'UFUK ÜNİVERSİTESİ', :email => 'ufuk.edu.tr')
University.create(:name => 'ULUDAĞ ÜNİVERSİTESİ', :email => 'uludag.edu.tr')
University.create(:name => 'ULUSLARARASI ANTALYA ÜNİVERSİTESİ', :email => 'antalya.edu.tr')
University.create(:name => 'UŞAK ÜNİVERSİTESİ', :email => 'usak.edu.tr')
University.create(:name => 'ÜSKÜDAR ÜNİVERSİTESİ', :email => 'uskudar.edu.tr')
University.create(:name => 'YALOVA ÜNİVERSİTESİ', :email => 'yalova.edu.tr')
University.create(:name => 'YAŞAR ÜNİVERSİTESİ', :email => 'yasar.edu.tr')
University.create(:name => 'YEDİTEPE ÜNİVERSİTESİ', :email => 'yeditepe.edu.tr')
University.create(:name => 'YENİ YÜZYIL ÜNİVERSİTESİ', :email => 'yeniyuzyil.edu.tr')
University.create(:name => 'YILDIRIM BEYAZIT ÜNİVERSİTESİ', :email => 'ybu.edu.tr')
University.create(:name => 'YILDIZ TEKNİK ÜNİVERSİTESİ', :email => 'yildiz.edu.tr')
University.create(:name => 'YÜKSEK İHTİSAS ÜNİVERSİTESİ', :email => 'yiu.edu.tr')
University.create(:name => 'YÜZÜNCÜ YIL ÜNİVERSİTESİ', :email => 'yyu.edu.tr')
University.create(:name => 'ZİRVE ÜNİVERSİTESİ', :email => 'zirve.edu.tr')


oguz = User.new( :username => "turbulence6th", :password => "oguzTanrikulu123", :password_confirmation => "oguzTanrikulu123", :email => "oguz.tanrikulu@metu.edu.tr",
  :email_confirmation => "oguz.tanrikulu@metu.edu.tr", :name => "Oğuz", :surname => "Tanrıkulu", :gender => :male, :bulletin => true, :phone => "538-3595977", 
  :verified => true, :birthday => Time.new(1994, 4, 3 ), :role => :admin )
oguz.university = University.find_by_email('metu.edu.tr')
oguz.save







onur = User.new( :username => "svmszcck", :password => "1234Onur1234", :password_confirmation => "1234Onur1234", :email => "demirtas.onur@metu.edu.tr",
  :email_confirmation => "demirtas.onur@metu.edu.tr", :name => "Onur", :surname => "Demirtaş", :gender => :male, :bulletin => true, :phone => "505-7822777", 
  :verified => true, :birthday => Time.new(1991, 8, 14 ), :role => :admin )
onur.university = University.find_by_email('metu.edu.tr')
onur.save 
